import type { HeroDef } from "../types";

export const heroes: HeroDef[] = [
  {
    id: "guanyu",
    artId: "guanyu",
    factionId: "shu",
    name: "關羽",
    title: "青龍武聖",
    role: "近戰掃蕩",
    passiveName: "義絕",
    passiveText: "刀系與連擊傷害提高，適合穩定清場。",
    baseStats: { maxHp: 150, moveSpeed: 220, armor: 4, pickupRadius: 96 },
    autoAbility: {
      id: "guanyu_auto",
      ownerHeroId: "guanyu",
      name: "青龍偃月",
      description: "自動揮出弧形青龍刀光，橫掃身前敵軍。",
      trigger: "auto",
      cooldown: 1.05,
      range: 270,
      radius: 76,
      damage: 28,
      damageTags: ["blade"],
      vfxKey: "qinglong_arc",
      effectId: "arc_sweep"
    },
    manualAbility: {
      id: "guanyu_manual",
      ownerHeroId: "guanyu",
      name: "拖刀斬",
      description: "蓄勢斬出長距離青龍刀氣，貫穿一路敵人。",
      trigger: "manual",
      cooldown: 7.5,
      range: 620,
      radius: 44,
      damage: 88,
      damageTags: ["blade", "shock"],
      vfxKey: "dragon_slash",
      effectId: "dragon_slash"
    },
    portraitKey: "portrait_guanyu",
    spriteKey: "hero_guanyu"
  },
  {
    id: "zhaoyun",
    artId: "zhaoyun",
    factionId: "shu",
    name: "趙雲",
    title: "常山白龍",
    role: "突進穿刺",
    passiveName: "白龍膽",
    passiveText: "冷卻更短，靠高速槍影切開包圍。",
    baseStats: { maxHp: 126, moveSpeed: 260, armor: 2, pickupRadius: 104 },
    autoAbility: {
      id: "zhaoyun_auto",
      ownerHeroId: "zhaoyun",
      name: "槍影連刺",
      description: "自動對前方敵人連續穿刺，射程較遠。",
      trigger: "auto",
      cooldown: 0.72,
      range: 420,
      radius: 24,
      damage: 20,
      damageTags: ["pierce"],
      vfxKey: "spear_flash",
      effectId: "spear_flurry"
    },
    manualAbility: {
      id: "zhaoyun_manual",
      ownerHeroId: "zhaoyun",
      name: "七進七出",
      description: "向目標方向突進，穿敵並留下白龍槍芒。",
      trigger: "manual",
      cooldown: 6.3,
      range: 360,
      radius: 58,
      damage: 62,
      damageTags: ["pierce", "shock"],
      vfxKey: "dragon_dash",
      effectId: "seven_dashes"
    },
    portraitKey: "portrait_zhaoyun",
    spriteKey: "hero_zhaoyun"
  },
  {
    id: "caocao",
    artId: "caocao",
    factionId: "wei",
    name: "曹操",
    title: "魏武帝星",
    role: "軍令支援",
    passiveName: "霸業雄心",
    passiveText: "親衛劍令能穩定追擊遠處敵人。",
    baseStats: { maxHp: 136, moveSpeed: 220, armor: 5, pickupRadius: 100 },
    autoAbility: {
      id: "caocao_auto",
      ownerHeroId: "caocao",
      name: "魏武劍令",
      description: "召出親衛劍氣，自動追擊最近的敵人。",
      trigger: "auto",
      cooldown: 1.1,
      range: 430,
      radius: 26,
      damage: 24,
      damageTags: ["command", "blade"],
      vfxKey: "wei_swords",
      effectId: "guard_swords"
    },
    manualAbility: {
      id: "caocao_manual",
      ownerHeroId: "caocao",
      name: "魏武令",
      description: "下令虎豹騎沿直線衝鋒，震散成群敵軍。",
      trigger: "manual",
      cooldown: 8,
      range: 720,
      radius: 56,
      damage: 76,
      damageTags: ["command", "shock"],
      vfxKey: "tiger_cavalry",
      effectId: "tiger_cavalry"
    },
    portraitKey: "portrait_caocao",
    spriteKey: "hero_caocao"
  },
  {
    id: "xiahoudun",
    artId: "xiahoudun",
    factionId: "wei",
    name: "夏侯惇",
    title: "獨眼豪刃",
    role: "重斬坦克",
    passiveName: "不屈",
    passiveText: "血量越低，重刀傷害越高。",
    baseStats: { maxHp: 172, moveSpeed: 205, armor: 6, pickupRadius: 88 },
    autoAbility: {
      id: "xiahoudun_auto",
      ownerHeroId: "xiahoudun",
      name: "重刀震退",
      description: "揮出沉重斬擊，擊退近身敵軍。",
      trigger: "auto",
      cooldown: 1.18,
      range: 250,
      radius: 90,
      damage: 30,
      damageTags: ["blade", "shock"],
      vfxKey: "iron_cleave",
      effectId: "heavy_cleave"
    },
    manualAbility: {
      id: "xiahoudun_manual",
      ownerHeroId: "xiahoudun",
      name: "獨眼血戰",
      description: "短暫狂暴，獲得吸血並提高斬擊範圍。",
      trigger: "manual",
      cooldown: 9,
      range: 210,
      radius: 140,
      damage: 54,
      damageTags: ["blade", "shock"],
      vfxKey: "blood_rage",
      effectId: "blood_rage"
    },
    portraitKey: "portrait_xiahoudun",
    spriteKey: "hero_xiahoudun"
  },
  {
    id: "zhouyu",
    artId: "zhouyu",
    factionId: "wu",
    name: "周瑜",
    title: "赤壁雅火",
    role: "火場控場",
    passiveName: "焚風",
    passiveText: "火焰持續時間與火場範圍提高。",
    baseStats: { maxHp: 118, moveSpeed: 230, armor: 2, pickupRadius: 112 },
    autoAbility: {
      id: "zhouyu_auto",
      ownerHeroId: "zhouyu",
      name: "琴音火彈",
      description: "彈出火焰音符，命中後造成燃燒。",
      trigger: "auto",
      cooldown: 0.9,
      range: 460,
      radius: 30,
      damage: 18,
      damageTags: ["fire"],
      vfxKey: "fire_note",
      effectId: "fire_note"
    },
    manualAbility: {
      id: "zhouyu_manual",
      ownerHeroId: "zhouyu",
      name: "赤壁火陣",
      description: "在戰場鋪開火陣，持續灼燒大片敵軍。",
      trigger: "manual",
      cooldown: 8.5,
      range: 380,
      radius: 168,
      damage: 36,
      damageTags: ["fire", "command"],
      vfxKey: "red_cliff_fire",
      effectId: "red_cliff_fire"
    },
    portraitKey: "portrait_zhouyu",
    spriteKey: "hero_zhouyu"
  },
  {
    id: "sunshangxiang",
    artId: "sunshangxiang",
    factionId: "wu",
    name: "孫尚香",
    title: "弓腰姬",
    role: "遠程箭幕",
    passiveName: "驍姬",
    passiveText: "拾取範圍更大，箭幕更容易連鎖清怪。",
    baseStats: { maxHp: 116, moveSpeed: 248, armor: 2, pickupRadius: 120 },
    autoAbility: {
      id: "sunshangxiang_auto",
      ownerHeroId: "sunshangxiang",
      name: "雙弩連射",
      description: "以雙弩扇形連射，快速削弱群體敵人。",
      trigger: "auto",
      cooldown: 0.78,
      range: 500,
      radius: 18,
      damage: 15,
      damageTags: ["arrow", "pierce"],
      vfxKey: "crossbow_fan",
      effectId: "fan_bolts"
    },
    manualAbility: {
      id: "sunshangxiang_manual",
      ownerHeroId: "sunshangxiang",
      name: "連環箭雨",
      description: "召喚大範圍箭幕落下，清除包圍圈。",
      trigger: "manual",
      cooldown: 7.2,
      range: 420,
      radius: 112,
      damage: 46,
      damageTags: ["arrow", "fire"],
      vfxKey: "arrow_rain",
      effectId: "arrow_rain"
    },
    portraitKey: "portrait_sunshangxiang",
    spriteKey: "hero_sunshangxiang"
  },
  {
    id: "diaochan",
    artId: "diaochan",
    factionId: "qun",
    name: "貂蟬",
    title: "傾城舞姬",
    role: "近戰舞者",
    passiveName: "花鈴步",
    passiveText: "近戰旋舞範圍更大，靠靈巧走位貼身割草。",
    baseStats: { maxHp: 124, moveSpeed: 252, armor: 2, pickupRadius: 116 },
    autoAbility: {
      id: "diaochan_auto",
      ownerHeroId: "diaochan",
      name: "花影旋舞",
      description: "在身邊旋出粉金花瓣斬，連續切開近距離敵軍。",
      trigger: "auto",
      cooldown: 0.86,
      range: 230,
      radius: 104,
      damage: 23,
      damageTags: ["blade", "charm"],
      vfxKey: "petal_waltz",
      effectId: "petal_waltz"
    },
    manualAbility: {
      id: "diaochan_manual",
      ownerHeroId: "diaochan",
      name: "傾城舞陣",
      description: "展開華麗舞陣，造成連續花瓣傷害並短暫迷亂敵人。",
      trigger: "manual",
      cooldown: 7.8,
      range: 280,
      radius: 158,
      damage: 48,
      damageTags: ["blade", "charm", "shock"],
      vfxKey: "allure_dance",
      effectId: "allure_dance"
    },
    portraitKey: "portrait_diaochan",
    spriteKey: "hero_diaochan"
  }
];

export const heroById = Object.fromEntries(heroes.map((hero) => [hero.id, hero])) as Record<HeroDef["id"], HeroDef>;
